#!/usr/bin/env bash
# setup-flatpak-fonts.sh: Automate font prioritization for Flatpak apps.

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_NAME="$(basename "$0")"
GEN_MARKER="Generated by ${SCRIPT_NAME}"

# --- Utilities ---

log() {
    printf '%s\n' "$*"
}

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

on_error() {
    local exit_code=$?
    local line_no=${1:-unknown}
    printf 'Error: command failed at line %s (exit: %s).\n' "$line_no" "$exit_code" >&2
    exit "$exit_code"
}

on_interrupt() {
    printf '\nAborted by user.\n' >&2
    exit 130
}

trap 'on_error $LINENO' ERR
trap on_interrupt INT

is_interactive() {
    [[ -t 0 && -t 1 ]]
}

require_interactive() {
    is_interactive || die "Interactive mode requires a TTY. Use flags (install --lang/--font) for non-interactive use."
}

require_cmd() {
    local cmd=$1
    command -v "$cmd" >/dev/null 2>&1 || die "Required command '$cmd' is not installed."
}

trim() {
    local s=$1
    s=$(printf '%s' "$s" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    printf '%s' "$s"
}

normalize_lang_code() {
    local value=$1
    value=$(trim "$value")
    value=$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')
    printf '%s' "$value"
}

validate_lang_code() {
    local value
    value=$(normalize_lang_code "$1")
    [[ "$value" =~ ^[a-z]{2}(-[a-z]{2})?$ ]]
}

xml_escape() {
    local s=$1
    s=${s//&/&amp;}
    s=${s//</&lt;}
    s=${s//>/&gt;}
    s=${s//\"/&quot;}
    s=${s//\'/&apos;}
    printf '%s' "$s"
}

extract_first_font_from_conf() {
    local file=$1
    awk -F'[<>]' '/<string>/{print $3; exit}' "$file"
}

prompt_yes_no() {
    local question=$1
    local default=${2:-N}
    local hint answer

    case "$default" in
        Y|y) hint="[Y/n]" ;;
        *) hint="[y/N]" ;;
    esac

    while true; do
        read -r -p "$question $hint: " answer || return 1
        answer=$(trim "$answer")

        if [[ -z "$answer" ]]; then
            answer=$default
        fi

        case "$answer" in
            Y|y|yes|YES) return 0 ;;
            N|n|no|NO) return 1 ;;
            *) log "Please answer y or n." ;;
        esac
    done
}

get_repo_root() {
    if command -v git >/dev/null 2>&1; then
        git rev-parse --show-toplevel 2>/dev/null || dirname "$(dirname "$(readlink -f "$0")")"
    else
        dirname "$(dirname "$(readlink -f "$0")")"
    fi
}

show_usage() {
    cat <<EOF
Usage:
  $0                                         Start interactive install wizard
  $0 install                                 Start interactive install wizard
  $0 install --lang <code> [--font <name>] [--all] [--force]
  $0 <lang-code> <font-family> [all]         Legacy quick mode (still supported)
  $0 list                                    List configured fonts
  $0 uninstall [<lang-code>]                 Interactive or quick uninstall
  $0 -h | --help                             Show this help

Examples:
  $0 install --lang th --font "Noto Sans Thai" --all
  $0 install --lang ja                       Pick font interactively for Japanese
  $0 th "Noto Sans Thai" all
  $0 uninstall th
EOF
}

check_install_dependencies() {
    require_cmd flatpak
    require_cmd fc-cache
    require_cmd fc-list
    require_cmd fc-match
    require_cmd find
    require_cmd awk
    require_cmd sed
}

check_uninstall_dependencies() {
    require_cmd fc-cache
    require_cmd find
    require_cmd awk
    require_cmd sed
}

parse_install_args() {
    local positional=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -l|--lang)
                [[ -n "${2:-}" ]] || die "Missing value for $1"
                LANG_CODE="$2"
                shift 2
                ;;
            -f|--font)
                [[ -n "${2:-}" ]] || die "Missing value for $1"
                FONT_FAMILY="$2"
                shift 2
                ;;
            -a|--all)
                APPLY_ALL="all"
                shift
                ;;
            --force|-y|--yes)
                FORCE_OVERWRITE="1"
                shift
                ;;
            -i|--interactive)
                FORCE_INTERACTIVE="1"
                shift
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            --)
                shift
                while [[ $# -gt 0 ]]; do
                    positional+=("$1")
                    shift
                done
                ;;
            -* )
                die "Unknown option: $1"
                ;;
            *)
                positional+=("$1")
                shift
                ;;
        esac
    done

    # Backward-compatible positional mode: <lang> <font> [all]
    if [[ ${#positional[@]} -ge 1 && -z "${LANG_CODE:-}" ]]; then
        LANG_CODE="${positional[0]}"
    fi
    if [[ ${#positional[@]} -ge 2 && -z "${FONT_FAMILY:-}" ]]; then
        FONT_FAMILY="${positional[1]}"
    fi
    if [[ ${#positional[@]} -ge 3 && "${positional[2]}" == "all" ]]; then
        APPLY_ALL="all"
    fi

    if [[ ${#positional[@]} -gt 3 ]]; then
        die "Too many arguments for install. See --help."
    fi
}

build_common_languages() {
    declare -gA COMMON_LANGS=(
        ["ar"]="Arabic"
        ["bn"]="Bengali"
        ["de"]="German"
        ["en"]="English"
        ["es"]="Spanish"
        ["fr"]="French"
        ["gu"]="Gujarati"
        ["he"]="Hebrew"
        ["hi"]="Hindi"
        ["ja"]="Japanese"
        ["ko"]="Korean"
        ["ml"]="Malayalam"
        ["mr"]="Marathi"
        ["nb"]="Norwegian"
        ["pa"]="Punjabi"
        ["pt"]="Portuguese"
        ["ru"]="Russian"
        ["sa"]="Sanskrit"
        ["sv"]="Swedish"
        ["ta"]="Tamil"
        ["te"]="Telugu"
        ["th"]="Thai"
        ["uk"]="Ukrainian"
        ["vi"]="Vietnamese"
        ["zh-cn"]="Chinese (Simplified)"
        ["zh-tw"]="Chinese (Traditional)"
    )
}

# --- Interactive flows ---

run_interactive_install() {
    require_interactive
    build_common_languages

    log "--- Flatpak Font Setup Wizard ---"
    log ""

    if [[ -n "${LANG_CODE:-}" ]]; then
        LANG_CODE=$(normalize_lang_code "$LANG_CODE")
        validate_lang_code "$LANG_CODE" || die "Invalid language code '$LANG_CODE'."
        log "Language pre-selected: $LANG_CODE (${COMMON_LANGS[$LANG_CODE]:-custom})"
    else
        log "Select a language:"
        local lang_codes
        mapfile -t lang_codes < <(printf '%s\n' "${!COMMON_LANGS[@]}" | sort)
        lang_codes+=("Other")

        PS3="Enter your choice (1-${#lang_codes[@]}): "
        select lang in "${lang_codes[@]}"; do
            if [[ "$lang" == "Other" ]]; then
                read -r -p "Enter language code (e.g., ja, ko, zh-cn): " LANG_CODE
                LANG_CODE=$(normalize_lang_code "$LANG_CODE")
                if ! validate_lang_code "$LANG_CODE"; then
                    log "Invalid format. Use codes like 'ja' or 'zh-cn'."
                    continue
                fi
                break
            elif [[ -n "$lang" && -n "${COMMON_LANGS[$lang]:-}" ]]; then
                LANG_CODE="$lang"
                break
            else
                log "Invalid selection. Choose a number from the list."
            fi
        done
        unset PS3
    fi

    log ""
    log "Searching for fonts supporting '$LANG_CODE'..."

    local fonts
    fonts=$(fc-list ":lang=$LANG_CODE" family 2>/dev/null | tr ',' '\n' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d' | sort -u || true)

    if [[ -z "$fonts" ]]; then
        die "No fonts found for language '$LANG_CODE'. Install a font that supports this language first."
    fi

    local font_count
    font_count=$(printf '%s\n' "$fonts" | wc -l | xargs)
    log "Found $font_count font(s) supporting '$LANG_CODE'"
    log ""

    if [[ -n "${FONT_FAMILY:-}" ]]; then
        FONT_FAMILY=$(trim "$FONT_FAMILY")
        [[ -n "$FONT_FAMILY" ]] || die "Font family cannot be empty."
        log "Font pre-selected: $FONT_FAMILY"
    else
        log "Select a font family:"
        local font_array=()
        while IFS= read -r line; do
            [[ -n "$line" ]] && font_array+=("$line")
        done <<<"$fonts"

        font_array+=("Enter manually...")

        if [[ ${#font_array[@]} -eq 2 ]]; then
            FONT_FAMILY="${font_array[0]}"
            log "Only one detected font: $FONT_FAMILY"
        else
            PS3="Enter your choice (1-${#font_array[@]}): "
            select font in "${font_array[@]}"; do
                if [[ "$font" == "Enter manually..." ]]; then
                    read -r -p "Enter font family name exactly: " FONT_FAMILY
                    FONT_FAMILY=$(trim "$FONT_FAMILY")
                    [[ -n "$FONT_FAMILY" ]] || { log "Font name cannot be empty."; continue; }
                    break
                elif [[ -n "$font" ]]; then
                    FONT_FAMILY="$font"
                    break
                else
                    log "Invalid selection. Choose a number from the list."
                fi
            done
            unset PS3
        fi
    fi

    # Validation (best effort)
    if ! fc-list ":family=$FONT_FAMILY" family 2>/dev/null | grep -Fqi "$FONT_FAMILY"; then
        prompt_yes_no "Warning: Font '$FONT_FAMILY' was not found exactly. Proceed anyway?" "N" || {
            log "Aborted."
            exit 0
        }
    fi

    log ""
    if [[ -n "${APPLY_ALL:-}" ]]; then
        log "Apply to all apps: yes (pre-selected)"
    else
        if prompt_yes_no "Apply to ALL installed Flatpak apps? (recommended)" "N"; then
            APPLY_ALL="all"
        else
            APPLY_ALL=""
        fi
    fi

    log ""
    log "========================================"
    log "Summary:"
    log "  Language: $LANG_CODE (${COMMON_LANGS[$LANG_CODE]:-custom})"
    log "  Font:     $FONT_FAMILY"
    log "  Apply to all apps: ${APPLY_ALL:-no}"
    log "========================================"
    prompt_yes_no "Proceed with installation?" "N" || {
        log "Aborted."
        exit 0
    }
}

run_interactive_uninstall() {
    require_interactive

    local conf_dir="$HOME/.config/fontconfig/conf.d"

    log "--- Flatpak Font Uninstall Wizard ---"
    log ""

    if [[ ! -d "$conf_dir" ]]; then
        log "No font configuration directory found at $conf_dir"
        exit 0
    fi

    local files
    files=$(find "$conf_dir" -maxdepth 1 -type f -name "99-*-fonts.conf" -printf "%f\n" | sort)

    if [[ -z "$files" ]]; then
        log "No custom font configurations found."
        exit 0
    fi

    log "Configured language fonts:"
    log ""

    local file_array=()
    local lang_array=()
    while IFS= read -r file; do
        [[ -n "$file" ]] || continue
        local lang
        lang=$(echo "$file" | sed 's/^99-//;s/-fonts.conf$//')
        local font_name
        font_name=$(extract_first_font_from_conf "$conf_dir/$file")

        file_array+=("$file")
        lang_array+=("$lang")

        printf '  [%d] %-10s -> %s\n' "${#file_array[@]}" "$lang" "${font_name:-unknown}"
    done <<<"$files"

    log ""
    while true; do
        read -r -p "Select a configuration to remove (Enter to cancel): " REPLY
        REPLY=$(trim "$REPLY")

        if [[ -z "$REPLY" ]]; then
            log "Aborted."
            exit 0
        fi

        if [[ "$REPLY" =~ ^[0-9]+$ ]] && (( REPLY >= 1 && REPLY <= ${#file_array[@]} )); then
            break
        fi

        log "Invalid selection. Enter a number between 1 and ${#file_array[@]}."
    done

    local idx=$((REPLY - 1))
    local lang="${lang_array[$idx]}"

    prompt_yes_no "Remove configuration for '$lang'?" "N" || {
        log "Aborted."
        exit 0
    }

    LANG_CODE="$lang"
}

# --- Core actions ---

write_lang_conf() {
    local conf_file=$1
    local lang=$2
    local font=$3

    local xlang xfont
    xlang=$(xml_escape "$lang")
    xfont=$(xml_escape "$font")

    cat >"$conf_file" <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <!-- $GEN_MARKER -->
  <!-- Force $xfont for $xlang language -->

  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>$xfont</family>
    </prefer>
  </alias>
  <alias>
    <family>serif</family>
    <prefer>
      <family>$xfont</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>$xfont</family>
    </prefer>
  </alias>

  <match target="pattern">
    <test name="lang" compare="eq">
      <string>$xlang</string>
    </test>
    <edit name="family" mode="prepend" binding="strong">
      <string>$xfont</string>
    </edit>
  </match>

  <match target="pattern">
    <test name="lang" compare="contains">
      <string>$xlang</string>
    </test>
    <edit name="family" mode="prepend" binding="strong">
      <string>$xfont</string>
    </edit>
  </match>
</fontconfig>
EOF
}

apply_per_app_configs() {
    local lang=$1
    local font=$2

    log "Applying per-app fontconfig for ALL installed Flatpak apps..."

    local count=0
    while IFS= read -r app_id; do
        [[ -n "$app_id" ]] || continue

        local app_conf_dir="$HOME/.var/app/$app_id/config/fontconfig"
        local app_conf_file="$app_conf_dir/fonts.conf"

        mkdir -p "$app_conf_dir"

        if [[ -f "$app_conf_file" && ! -f "${app_conf_file}.bak" ]]; then
            cp "$app_conf_file" "${app_conf_file}.bak"
        fi

        local xlang xfont
        xlang=$(xml_escape "$lang")
        xfont=$(xml_escape "$font")

        cat >"$app_conf_file" <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <!-- $GEN_MARKER -->
  <!-- Per-app font override for $app_id -->
  <!-- Force $xfont for $xlang language -->

  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>$xfont</family>
    </prefer>
  </alias>
  <alias>
    <family>serif</family>
    <prefer>
      <family>$xfont</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>$xfont</family>
    </prefer>
  </alias>

  <match target="pattern">
    <test name="lang" compare="eq">
      <string>$xlang</string>
    </test>
    <edit name="family" mode="prepend" binding="strong">
      <string>$xfont</string>
    </edit>
  </match>

  <match target="pattern">
    <test name="lang" compare="contains">
      <string>$xlang</string>
    </test>
    <edit name="family" mode="prepend" binding="strong">
      <string>$xfont</string>
    </edit>
  </match>
</fontconfig>
EOF

        log "  Applied to: $app_id"
        count=$((count + 1))
    done < <(flatpak list --app --columns=application 2>/dev/null || true)

    log "  Total apps configured: $count"
}

cleanup_per_app_configs() {
    local lang=$1
    local removed=0
    local app_conf_file

    while IFS= read -r app_conf_file; do
        [[ -f "$app_conf_file" ]] || continue
        if grep -Fq "$GEN_MARKER" "$app_conf_file" && grep -Fq "<string>$lang</string>" "$app_conf_file"; then
            rm -f "$app_conf_file"
            removed=$((removed + 1))
        fi
    done < <(find "$HOME/.var/app" -type f -path '*/config/fontconfig/fonts.conf' 2>/dev/null || true)

    if (( removed > 0 )); then
        log "Removed $removed generated per-app font config(s)."
    fi
}

install_logic() {
    local lang font apply_all repo_root
    lang=$(normalize_lang_code "$1")
    font=$(trim "$2")
    apply_all="${3:-}"
    repo_root="$4"

    validate_lang_code "$lang" || die "Invalid language code '$lang'. Use forms like 'th' or 'zh-cn'."
    [[ -n "$font" ]] || die "Font family cannot be empty."

    local conf_dir="$HOME/.config/fontconfig/conf.d"
    local conf_file="$conf_dir/99-$lang-fonts.conf"

    log "--- Setting up '$font' for language: $lang ---"
    mkdir -p "$conf_dir"

    if [[ -f "$conf_file" ]]; then
        if [[ "${FORCE_OVERWRITE:-0}" == "1" ]]; then
            log "Overwriting existing config: $conf_file (--force)"
        else
            if is_interactive; then
                prompt_yes_no "Config exists at $conf_file. Overwrite?" "N" || {
                    log "Skipped updating $conf_file"
                    return
                }
            else
                die "Config already exists at $conf_file. Re-run with --force or use interactive mode."
            fi
        fi
        cp "$conf_file" "${conf_file}.bak"
    fi

    local repo_conf_file="$repo_root/.config/fontconfig/conf.d/99-$lang-fonts.conf"
    if [[ -f "$repo_conf_file" ]]; then
        log "Found existing config in repository: $repo_conf_file"
        cp "$repo_conf_file" "$conf_file"
    else
        log "Generating new configuration at $conf_file"
        write_lang_conf "$conf_file" "$lang" "$font"
    fi

    log "Applying global Flatpak overrides..."
    flatpak override --user \
        --filesystem=xdg-config/fontconfig:ro \
        --filesystem=~/.config/fontconfig:ro \
        --filesystem=~/.local/share/fonts:ro \
        --filesystem=/usr/share/fonts:ro \
        --filesystem=/usr/share/fontconfig:ro

    if [[ "$apply_all" == "all" ]]; then
        log ""
        apply_per_app_configs "$lang" "$font"
    fi

    log "Refreshing font cache..."
    fc-cache -f

    log ""
    log "=== VERIFICATION ==="
    log "Host system font match:"
    fc-match ":lang=$lang" || true

    log ""
    log "Flatpak runtime font match:"
    flatpak run --command=fc-match --app=org.freedesktop.Platform//24.08 ":lang=$lang" 2>/dev/null || \
        flatpak run --command=fc-match --app=org.freedesktop.Platform//23.08 ":lang=$lang" 2>/dev/null || \
        log "(Could not test: no compatible Freedesktop runtime available)"

    log ""
    log "Done. Restart Flatpak apps to apply changes."
}

uninstall_logic() {
    local lang
    lang=$(normalize_lang_code "$1")
    validate_lang_code "$lang" || die "Invalid language code '$lang'."

    local conf_file="$HOME/.config/fontconfig/conf.d/99-$lang-fonts.conf"

    if [[ -f "$conf_file" ]]; then
        log "Removing font configuration: $conf_file"
        rm -i "$conf_file"
        cleanup_per_app_configs "$lang"
        log "Refreshing font cache..."
        fc-cache -f
        log "Uninstalled font config for '$lang'."
    else
        log "No configuration found for language '$lang' at $conf_file"
    fi
}

list_configs() {
    local conf_dir="$HOME/.config/fontconfig/conf.d"

    log "--- Configured Font Overrides ---"
    log ""

    if [[ ! -d "$conf_dir" ]]; then
        log "No font configurations found."
        exit 0
    fi

    local files
    files=$(find "$conf_dir" -maxdepth 1 -type f -name "99-*-fonts.conf" -printf "%f\n" | sort)

    if [[ -z "$files" ]]; then
        log "No custom font configurations found."
        exit 0
    fi

    printf '%-12s %s\n' "LANGUAGE" "FONT"
    echo "-----------------------------------"

    while IFS= read -r file; do
        [[ -n "$file" ]] || continue
        local lang
        lang=$(echo "$file" | sed 's/^99-//;s/-fonts.conf$//')
        local font_name
        font_name=$(extract_first_font_from_conf "$conf_dir/$file")
        printf '%-12s %s\n' "$lang" "${font_name:-unknown}"
    done <<<"$files"

    log ""
    log "To uninstall: $0 uninstall <lang-code>"
}

# --- Main ---

REPO_ROOT=$(get_repo_root)
LANG_CODE="${LANG_CODE:-}"
FONT_FAMILY="${FONT_FAMILY:-}"
APPLY_ALL="${APPLY_ALL:-}"
FORCE_INTERACTIVE="${FORCE_INTERACTIVE:-0}"
FORCE_OVERWRITE="${FORCE_OVERWRITE:-0}"

if [[ $# -eq 0 ]]; then
    check_install_dependencies
    run_interactive_install
    install_logic "$LANG_CODE" "$FONT_FAMILY" "$APPLY_ALL" "$REPO_ROOT"
    exit 0
fi

case "$1" in
    -h|--help|help)
        show_usage
        ;;
    list)
        list_configs
        ;;
    uninstall)
        check_uninstall_dependencies
        if [[ -z "${2:-}" ]]; then
            run_interactive_uninstall
            uninstall_logic "$LANG_CODE"
        else
            uninstall_logic "$2"
        fi
        ;;
    install)
        shift
        check_install_dependencies
        parse_install_args "$@"

        if [[ "$FORCE_INTERACTIVE" == "1" || -z "$LANG_CODE" || -z "$FONT_FAMILY" ]]; then
            run_interactive_install
        fi
        install_logic "$LANG_CODE" "$FONT_FAMILY" "$APPLY_ALL" "$REPO_ROOT"
        ;;
    *)
        check_install_dependencies
        parse_install_args "$@"
        if [[ "$FORCE_INTERACTIVE" == "1" || -z "$LANG_CODE" || -z "$FONT_FAMILY" ]]; then
            run_interactive_install
        fi
        install_logic "$LANG_CODE" "$FONT_FAMILY" "$APPLY_ALL" "$REPO_ROOT"
        ;;
esac
